set(One_FOUND TRUE)
set(One_aa AAAAA)


#find_package(Python3)
#if (Python3_FOUND)
#    message(STATUS "Python3_FOUND is ${Python3_FOUND}")
#    message(STATUS "Python3_Interpreter_FOUND is ${Python3_Interpreter_FOUND}")
#    message(STATUS "Python3_EXECUTABLE is ${Python3_EXECUTABLE}")
#    message(STATUS "Python3_INTERPRETER_ID is ${Python3_INTERPRETER_ID}")
#    message(STATUS "Python3_STDLIB is ${Python3_STDLIB}")
#    message(STATUS "Python3_STDARCH is ${Python3_STDARCH}")
#    message(STATUS "Python3_SITELIB is ${Python3_SITELIB}")
#    message(STATUS "Python3_SITEARCH is ${Python3_SITEARCH}")
#    message(STATUS "Python3_SOABI is ${Python3_SOABI}")
#    message(STATUS "Python3_Compiler_FOUND is ${Python3_Compiler_FOUND}")
#    message(STATUS "Python3_COMPILER is ${Python3_COMPILER}")
#    message(STATUS "Python3_COMPILER_ID is ${Python3_COMPILER_ID}")
#    message(STATUS "Python3_Development_FOUND is ${Python3_Development_FOUND}")
#    message(STATUS "Python3_INCLUDE_DIRS is ${Python3_INCLUDE_DIRS}")
#    message(STATUS "Python3_LIBRARIES is ${Python3_LIBRARIES}")
#    message(STATUS "Python3_LIBRARY_DIRS is ${Python3_LIBRARY_DIRS}")
#    message(STATUS "Python3_RUNTIME_LIBRARY_DIRS is ${Python3_RUNTIME_LIBRARY_DIRS}")
#    message(STATUS "Python3_VERSION is ${Python3_VERSION}")
#    message(STATUS "Python3_VERSION_MAJOR is ${Python3_VERSION_MAJOR}")
#    message(STATUS "Python3_VERSION_MINOR is ${Python3_VERSION_MINOR}")
#    message(STATUS "Python3_VERSION_PATCH is ${Python3_VERSION_PATCH}")
#    message(STATUS "Python3_NumPy_FOUND is ${Python3_NumPy_FOUND}")
#    message(STATUS "Python3_NumPy_INCLUDE_DIRS is ${Python3_NumPy_INCLUDE_DIRS}")
#    message(STATUS "Python3_NumPy_VERSION is ${Python3_NumPy_VERSION}")
#endif ()